# Generated by Django 5.2.5 on 2025-09-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bot_created_at_bot_description_bot_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]