# Generated by Django 5.2.5 on 2025-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_about_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='botfuther_api_token_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='botfuther_api_token_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='botfuther_api_token_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='botfuther_api_token_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='botfuther_api_token_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]