# Generated by Django 5.2.5 on 2025-09-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_botfuther_api_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='bot_avatars/'),
        ),
    ]
